name: captivate
description: A network client, written in Dart, that talks to the captivate.fm podcast service.
version: 0.1.0
repository: https://github.com/flutter-bounty-hunters/captivate

environment:
  sdk: ^3.3.3

dependencies:
  dio: ^5.8.0+1
  http: ^1.2.1
  logging: ^1.3.0
  meta: ^1.15.0
  mime: ^2.0.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
